spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver              # mysql驱动包
    url: jdbc:mysql://192.168.27.134:3306/db_seckillgoods?useUnicode=true&characterEncoding=utf-8&useSSL=false              # 数据库名称
    username: root
    password: root
    dbcp2:
      min-idle: 5                                              # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间
  activemq:
    broker-url: tcp://192.168.27.134:61616 #activemq地址
    user: admin
    password: admin
    queues: seckill-queues
    pool:
      enabled: false

redis:
  host: 127.0.0.1
  port: 6379
  timeout: 10
  password: redis
  pool-max-idle: 500
  pool-max-total: 500
  pool-max-wait: 500


mybatis:
  type-aliases-package: com.yj.entites    # 所有Entity别名类所在包
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # spring boot集成mybatis的方式打印sql
    map-underscore-to-camel-case: true #驼峰
  mapper-locations:
    - classpath:mapper/*.xml                       # mapper映射文件


#设置feign客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnctTimeout: 5000
  
logging:
  level:
    # feign 日志以什么级别监控哪个接口
    com.zhao.demo.service.PaymentFeignService: debug


